### ISSUE TITLE
Splitter is a contravariant functor 

### ISSUE THREAD

**Issue by eayus** [byorgey/split#21]
The `Splitter` type seems to form a contravariant functor: given a splitter than works on `a` and a preprocessing step `b -> a`, we can get a splitter that works on `b`.

The package [cotravariant](https://hackage.haskell.org/package/contravariant-1.4/docs/Data-Functor-Contravariant.html) adds a type class for this, though if you wanted to avoid dependencies a simple function would also work.

Is this something you would consider adding to this library? I'd be happy to implement it.

**Comment by byorgey** [comment]
Hi @eayus , thanks for this suggestion!  I definitely do not want to add a dependency on the `contravariant` package, since the `split` package currently only has a dependency on `base`, and adding a bunch of dependencies could have a big impact (currently 7441 packages on Hackage import `split` either directly or transitively).

However, I think you are right that `Splitter` is a contravariant functor and I would be happy to merge a PR that adds a function to witness this.  Perhaps `mapSplitter :: (b -> a) -> Splitter a -> Splitter b`?  I'm open to other naming suggestions as well.

**Comment by eayus** [comment]
I agree and think that those are sensible names for the functions. I'll try to get around to submitting a PR in the next few days.

**Comment by Bodigrim** [comment]
> The package [cotravariant](https://hackage.haskell.org/package/contravariant-1.4/docs/Data-Functor-Contravariant.html) adds a type class for this, though if you wanted to avoid dependencies a simple function would also work.

`Contravariant` has been in `base` for quite a long time: https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Functor-Contravariant.html#t:Contravariant

**Comment by byorgey** [comment]
Oh, thanks @Bodigrim , I had forgotten that!  @eayus would you like to also add a `Contravariant` instance (just by setting `contramap = mapSplitter`)?
